# Generated by Django 3.2.25 on 2025-06-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', 'add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL to your avatar image (legacy)'),
        ),
    ]
